name: Backup Documentation to Dropbox

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'SOP/**'
      - 'Images/**'

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to Dropbox
        uses: andrejs-ps/upload-file-to-dropbox-action@v1.0.0
        with:
          token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          local_path: '.'
          remote_path: '/gitdocs/'
