name: Backup Documentation to Dropbox

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'SOP/**'
      - 'Images/**'

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync SOP folder to Dropbox
        uses: dandydev/dropbox-sync@v1.0.0
        with:
          access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          source_folder: 'SOP'
          destination_folder: '/gitdocs/SOP'

      - name: Sync Images folder to Dropbox
        uses: dandydev/dropbox-sync@v1.0.0
        with:
          access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          source_folder: 'Images'
          destination_folder: '/gitdocs/Images'
