name: Backup Documentation to Dropbox

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'SOP/**'
      - 'Images/**'

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to Dropbox
        uses: dropbox-actions/upload-to-dropbox@v1
        with:
          oauth_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          upload_path: '/gitdocs/'
          local_path: '.'
