name: Backup Documentation to Dropbox

on:
  push:
    branches:
      - main
      - master
    # Ce filtre permet d'exécuter le workflow uniquement si des fichiers
    # dans le dossier 'documentation' sont modifiés, ce qui est very efficace.
    paths:
      - 'documentation/**'

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload documentation to Dropbox
        uses: dandydev/dropbox-sync@v1.0.0
        with:
          access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          source_folder: 'documentation'
          destination_folder: '/gitdocs'
